name: Run Cypress tests on CI

on: 
 workflow_dispatch:
 push:
   branches:
     - master
 pull_request:
   types: [opened, synchronize, reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress Run
        uses: cypress-io/github-action@v6

      - name: Copy Mochawesome reports
        run: |
          mkdir -p mochawesome-report
          cp -r cypress/reports/mochawesome mochawesome-report

      - name: Publish Mochawesome reports
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: mochawesome-report