name: RunCypressTests

on: 
 workflow_dispatch:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress Run
        uses: cypress-io/github-action@v6
      
      - name: Merge Mochawesome reports
        run: |
          yarn run mochawesome-merge cypress/reports/mochawesome-report/*.json -o cypress/reports/mochawesome-report/output.json
          cp -f output.json mochawesome.json

      - name: Copy Mochawesome reports
        run: |
          mkdir -p mochawesome-report
          cp -r cypress/reports/mochawesome-report mochawesome-report

      - name: Publish Mochawesome reports
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: mochawesome-report
